name: deploy-website

# Only run this when the master branch changes
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

# This job installs dependencies, builds the website and pushes it to `gh-pages`
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build the site
        run: |
          sphinx-build -nW --keep-going -b html .  _build

      # # Hide pages behind a password
      # - uses: actions/setup-node@v3
      # - run: npm install -g staticrypt
      # - run: find _build/hidden -type f -name "*.html" -exec staticrypt {} TEST -o {} \;

      # If we've pushed to main, push the book's HTML to github-pages
      - if: ${{ github.ref == 'refs/heads/main' }}
        name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build
          # cname: website.com
